# Generated by Django 3.2.3 on 2021-07-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Departments',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
