# Generated by Django 3.2.3 on 2021-07-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_auto_20210704_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
